os: focal

env:
  - FOO=mon
  - FOO=tana

script: 
uname -r 
echo $Montana tests Travis

stages:
  - Compile
  - Test
  - Deploy

jobs:
  include:
    - stage: Compile
      script: 
      uname -r 
      echo Compile
      env: &env
        - FOO=
        - BAR=
    - stage: Deploy
      script: 
      uname -r
      echo Deploy
      <<: *env
